version: '3.8'
services:
  ui:
    build:
      context: .
      args:
        - VITE_API_URL=http://localhost:5058
    ports:
      - "8080:80"
    networks:
      - webnet
    environment:
      - VITE_API_URL=http://localhost:5058

networks:
  webnet:
    external: true
