version: '3.8'
services:
  ui:
    build:
      context: .
      args:
        - VITE_API_URL=http://3.145.26.78:5058
    ports:
      - "8080:80"
    networks:
      - webnet
    environment:
      - VITE_API_URL=http://3.145.26.78:5058
      - API_KEY=QnVydmVsYUFwaVNlY3VyaXR5IzEyMg=

networks:
  webnet:
    external: true
