version: '3.8'
services:
  ui:
    build:
      context: .
      args:
        - VITE_API_URL=${VITE_API_BASE_URL}
    ports:
      - "8080:80"
    networks:
      - webnet
    environment:
      - VITE_API_URL=${VITE_API_BASE_URL}
      - API_KEY=QnVydmVsYUFwaVNlY3VyaXR5IzEyMg=

networks:
  webnet:
    external: true
